---
# tasks file for gnome-workstation
- name: install packages
  package:
    name:
      - neovim
      - gnome-tweak-tool
      - gnome-shell-extension-activities-configurator
      - gnome-shell-extension-dash-to-dock
    state: present
- name: apply dconf settings
  copy:
    src: 00_site_settings
    dest: /etc/dconf/db/site.d/00_site_settings
- name: update dconf
  command: /usr/bin/dconf update
- name: ensure skel directory exists
  file:
    path: /etc/skel/.config/gtk-3.0
    state: directory
- name: import gtk.css
  copy:
    src: gtk.css
    dest: /etc/skel/.config/gtk-3.0/gtk.css
- name: apply gtk.css
  shell: for D in $(ls /home); do mkdir -p /home/$D/.config/gtk-3.0; cp /etc/skel/.config/gtk-3.0/gtk.css /home/$D/.config/gtk-3.0/gtk.css; chown -R $D:$D /home/$D/.config; done
  args:
    executable: /bin/bash
- name: gedit sucks
  replace:
    path: "{{ item }}"
    regexp: 'org.gnome.gedit.desktop'
    replace: 'nvim.desktop'
  loop:
    - /usr/share/applications/mimeapps.list
    - /usr/share/applications/gnome-mimeapps.list
