---
# tasks file for gnome-workstation
- name: install packages
  package:
    name:
      - gnome-tweak-tool
      - gnome-shell-extension-activities-configurator
      - gnome-shell-extension-dash-to-dock
    state: present
- name: apply dconf settings
  copy:
    src: 00_site_settings
    dest: /etc/dconf/db/site.d/00_site_settings
  notify: 
    - update dconf
- name: import gtk.css
  copy:
    src: gtk.css
    dest: /usr/share/gtk-3.0/gtk.css
  notify:
    - apply gtk.css
