---
bash_aliases:
  - alias: ll
    command: ls -Gla
  - alias: l
    command: ls -Gl
  - alias: dir
    command: ls
  - alias: fzf
    command: fzf --reverse
  - alias: k
    command: kubectl
  - alias: d
    command: docker
  - alias: gs
    command: git status
  - alias: gp
    command: git pull
  - alias: tf
    command: terraform
files:
  - src: gtk.css
    dest: /home/{{ apply_username }}/.config/gtk-3.0/gtk.css
  - src: .vimrc
    dest: /home/{{ apply_username }}/.vimrc
  - src: settings.json
    dest: /home/{{ apply_username }}/.config/Code/User/settings.json    
  - src: keybindings.json
    dest: /home/{{ apply_username }}/.config/Code/User/keybindings.json
