---
# tasks file for hashicorp
- name: install hashicorp products
  unarchive:
    src: "{{ item }}"
    dest: /usr/bin
    remote_src: yes
  loop:
    - https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip
    - https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    - https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_linux_amd64.zip
    - https://releases.hashicorp.com/vault/1.4.2/vault_1.4.2_linux_amd64.zip
