---
# tasks file for snap-apps
- name: install snapd
  package:
    name: snapd
    state: present
- name: enable snapd
  service:
    name: snapd
    enabled: yes
    state: started
- name: install snap apps
  snap:
    name:
      - discord
      - spotify
    state: present
